name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name : Checkout
      uses: actions/checkout@v6.1.0
    - name : Build
      working-directory: ./hasanhuseyin.tr
      run: docker build --build-arg VITE_YOUTUBE_API_KEY=${{ secrets.VITE_YOUTUBE_API_KEY }} -t hasanhuseyin.tr .